[versions]
vanniktech-maven-publish = "0.36.0"
agp = "8.13.2"
android-minSdk = "24"
#noinspection GradleDependency
android-compileSdk = "36"
#noinspection OldTargetApi
android-targetSdk = "36"

kotlin = "2.3.21"
compose-plugin = "1.10.3"
androidx-activityCompose = "1.13.0"
jetpack-compose-bom = "2026.04.01"
coroutines-bom = "1.10.2"
coil-bom = "3.4.0"
jvmTarget = "17"

dokka = "2.2.0"
kotlinxDatetime = "0.7.1"
navigationCompose = "2.9.2"

accompanist = "0.37.3"

[libraries]

compose-filepicker = { module = "com.vickyleu.kmp.filepicker:filepicker", version = "2.0.0" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-navigation-compose  = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "jetpack-compose-bom" }
coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "coroutines-bom" }
coil-bom = { module = "io.coil-kt.coil3:coil-bom", version.ref = "coil-bom" }

coil-core = { module = "io.coil-kt.coil3:coil"}
coil-compose = { module = "io.coil-kt.coil3:coil-compose"}
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }


[plugins]
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }